version: '3.8'

services:
  odoo:
    build: .
    container_name: odoo
    depends_on:
      - db
    ports:
      - 8069:8069
    networks:
      - odoo-network
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./additional-addons:/mnt/additional-addons
    logging:
      options:
        max-size: 10m
    #command: -- --dev=reload
    #command: --dev=qweb,xml
    command: -- --dev=all
    stdin_open: true
    tty: true

  db:
    image: postgres:14
    container_name: db
    networks:
      - odoo-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m

volumes:
  odoo-data:
  db-data:
networks:
  odoo-network:
